### ISSUE TITLE
Error Reading Query

### ISSUE THREAD

**Issue by rawkakani** [harankumar/DartFeed#4]
I can not read a rss that has a query in it 
for example https://example.cr/ex/?rss=1

**Comment by harankumar** [comment]
Could you provide some more details about the error you are experiencing? What exactly is the error message you are receiving? How specifically did you call the API? What site specifically were you trying to load? If the site you were trying to load was https://example.cr/ex/?rss=1, then DartFeed would likely throw an exception, as that site does not appear to be a valid RSS feed (it's showing up to me as a connection error).

I added two query based URLs ([Google News](https://news.google.com/news?pz=1&cf=all&ned=us&hl=en&q=dart+language&output=rss) and [Reddit](http://www.reddit.com/search.rss?q=batman)) to the tests, and they all still passed, so I'm not sure exactly how to reproduce this error.

Please provide more information so I can adequately address this issue.

**Comment by rawkakani** [comment]
The site is kickass a torrent site and i use the api the same way you showed it in the example , using and array of web feeds and using parser to go through each web feed, so when it reaches "https://kat.cr/tv/?rss=1"  it gives the error( Unhandled exception:
Uncaught Error: FormatException: Invalid character (at character 84)
...C3250767695E0E639FE65.torrent?title=[kat.cr]bahama.blue.series.1.1of6.bl...) 
                                       ^
So i guessed the was an error with the site code, but when i use another RSS reader it works specifically(RSS Merge and reader google chrome app)

So then i tried putting the XML code in a file and read from it it gives me the same error and then the debugger pops up and says the error happened at Uri.fail(), Uri.normalize(), Uri.makeQuery()

So I'm not sure if its the Uri API that doesn't support the feed or its the site with the problem

Because when i use a "RSS Merge and reader it works

Thank you for your time

**Comment by harankumar** [comment]
It appears the error is coming from `Uri.parse`, due to the presence of brackets in the URL. Interestingly, the method will apply escapes for any other invalid character and not throw any exception, unless that character is an open or close bracket. I added an issue for the Dart SDK [here](https://github.com/dart-lang/sdk/issues/23688), but in the meantime, all URLs will have to just be escaped manually.
Please update to version 0.0.2, and you should not receive any errors. Sorry for any inconvenience this may have caused. Add another issue if you experience any other problems.

**Comment by rawkakani** [comment]
Thank you
